AllCops:
  TargetRubyVersion: 2.5

LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - 'spec/**/*'
