version: '2.4'

services:
  base:
    build: 
      context: .
    volumes:
      - .:/app
      
  dev:
    extends:
      file: docker-compose.yml
      service: base
    environment:
      - APP_ENV=development
    command: sh
  
  test:
    extends:
      file: docker-compose.yml
      service: base
    environment:
      - APP_ENV=test
    command: bundle exec rake